name: code style

on: [push, pull_request]

jobs:
  pylint:
    runs-on: ubuntu-latest 
    
    steps: 
    - name: Clone repository
      uses: actions/checkout@v2
    
    - name: Set up Python 3.8 on ubuntu
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pylint
        
    - name: Lint with pylint
      run: |
        find . -iname "*.py" | xargs pylint --disable=C0114
